### ISSUE TITLE
error when starting up IOC 

### ISSUE THREAD

**Issue by LeeYangLBLBCS** [epics-motor/motorMotorSim#4]
I got these errors related to PV offset and resolution settings when using the latest motorMotorSim.
(Epics base 7.0.4).
Are they expected?

# The is the ASYN example for communication to 4 simulated motors
# "#!" marks lines that can be uncommented.
< envPaths
epicsEnvSet("IOC","iocMotorSim")
epicsEnvSet("TOP","/home/lyang/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorMotorSim/iocs/motorSimIOC")
epicsEnvSet("MOTOR","/home/lyang/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1")
epicsEnvSet("ASYN","/home/lyang/epics/modules/synApps_6_1_epics7/support/asyn-R4-38")
epicsEnvSet("SNCSEQ","/home/lyang/epics/modules/synApps_6_1_epics7/support/seq-2-2-6")
epicsEnvSet("BUSY","/home/lyang/epics/modules/synApps_6_1_epics7/support/busy-R1-7-2")
epicsEnvSet("IPAC","/home/lyang/epics/modules/synApps_6_1_epics7/support/ipac-2-15")
epicsEnvSet("EPICS_BASE","/home/lyang/epics/base-7.0.4")
epicsEnvSet("SUPPORT","/home/lyang/epics/modules/synApps_6_1_epics7/support")
dbLoadDatabase("/home/lyang/epics/modules/synApps_6_1_epics7/support/motor-R7-2-1/modules/motorMotorSim/iocs/motorSimIOC/dbd/motorSim.dbd")
motorSim_registerRecordDeviceDriver(pdbbase)
dbLoadTemplate("motor.substitutions")
# Create simulated motors: ( start card , start axis , low limit, high limit, home posn, # cards, # axes to setup)
motorSimCreate( 0, 0, -32000, 32000, 0, 1, 4 )
Creating motor simulator: card: 0, axis: 0, hi: 32000, low -32000, home: 0, ncards: 1, naxis: 4
Created motor for card 0, signal 0 OK
Created motor for card 0, signal 1 OK
Created motor for card 0, signal 2 OK
Created motor for card 0, signal 3 OK
# Setup the Asyn layer (portname, low-level driver drvet name, card, number of axes on card)
drvAsynMotorConfigure("motorSim1", "motorSim", 0, 4)
motorSimCreateController("motorSim2", 8)
#asynSetTraceIOMask("motorSim2", 0, 4)
#asynSetTraceMask("motorSim2", 0, 255)
# motorSimConfigAxis(port, axis, lowLimit, highLimit, home, start)
motorSimConfigAxis("motorSim2", 0, 20000, -20000,  500, 0)
motorSimDriver:motorSimConfigAxis: configuring controller motorSim2 axis 0
motorSimConfigAxis("motorSim2", 1, 20000, -20000, 1500, 0)
motorSimDriver:motorSimConfigAxis: configuring controller motorSim2 axis 1
motorSimConfigAxis("motorSim2", 2, 20000, -20000, 2500, 0)
motorSimDriver:motorSimConfigAxis: configuring controller motorSim2 axis 2
motorSimConfigAxis("motorSim2", 3, 20000, -20000, 3000, 0)
motorSimDriver:motorSimConfigAxis: configuring controller motorSim2 axis 3
iocInit
Starting iocInit
############################################################################
############################################################################
**IOC:m1Offset devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_OFFSET
Error (514,514) PV: IOC:m1Offset ao: init_record

IOC:m1Resolution devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_RESOLUTION
Error (514,514) PV: IOC:m1Resolution ao: init_record

IOC:m2Offset devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_OFFSET
Error (514,514) PV: IOC:m2Offset ao: init_record

IOC:m2Resolution devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_RESOLUTION
Error (514,514) PV: IOC:m2Resolution ao: init_record

IOC:m3Offset devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_OFFSET
Error (514,514) PV: IOC:m3Offset ao: init_record

IOC:m3Resolution devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_RESOLUTION
Error (514,514) PV: IOC:m3Resolution ao: init_record

IOC:m4Offset devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_OFFSET
Error (514,514) PV: IOC:m4Offset ao: init_record

IOC:m4Resolution devAsynFloat64::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_RESOLUTION
Error (514,514) PV: IOC:m4Resolution ao: init_record**

IOC:m1Direction devAsynInt32::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_DIRECTION
IOC:m2Direction devAsynInt32::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_DIRECTION
IOC:m3Direction devAsynInt32::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_DIRECTION
IOC:m4Direction devAsynInt32::initCommon drvUserCreate drvmotorAsyn::drvUserCreate, unknown command=MOTOR_REC_DIRECTION
iocRun: All initialization complete

**Comment by kmpeters** [comment]
Those errors are related to this issue:

https://github.com/epics-modules/motor/issues/166

You can safely ignore them.

**Comment by kmpeters** [comment]
This motor pull request added databases for model-2 asyn motor drivers that eliminate these errors:

https://github.com/epics-modules/motor/pull/197
