### ISSUE TITLE
Missing libraries when linking example application

### ISSUE THREAD

**Issue by MarkRivers** [epics-motor/motorMotorSim#5]
I am running the master branch of motor, and the master branch of all repositories under motor/modules.

I am having a problem when I link the example applications.  This happens for all modules, not just motorMotorSim, but it can be used as an example.

I did a "clean" at the top-level of motor and rebuilt it, and all the modules.

When I try to run the example application I get the following error:

```
corvette:motorSimIOC/bin/linux-x86_64>./motorSim
./motorSim: error while loading shared libraries: libasyn.so: cannot open shared object file: No such file or directory
```
When I run ldd on the example application I see this:
```
/home/epics/devel/motor/modules/motorMotorSim/iocs/motorSimIOC/bin/linux-x86_64
corvette:motorSimIOC/bin/linux-x86_64>ldd motorSim
        linux-vdso.so.1 =>  (0x00007ffcf470e000)
        libmotorSimSupport.so => /home/epics/devel/motor-7-0/lib/linux-x86_64/libmotorSimSupport.so (0x00007f36a3f5d000)
        libmotor.so => /home/epics/devel/motor-7-0/lib/linux-x86_64/libmotor.so (0x00007f36a3d3c000)
        libasyn.so => not found
        libseq.so => /home/epics/devel/seq-2-2-5/lib/linux-x86_64/libseq.so (0x00007f36a3b2c000)
        libpv.so => /home/epics/devel/seq-2-2-5/lib/linux-x86_64/libpv.so (0x00007f36a3928000)
        libdbRecStd.so.3.17.0 => /usr/local/epics/base/lib/linux-x86_64/libdbRecStd.so.3.17.0 (0x00007f36a36d4000)
        libdbCore.so.3.17.0 => /usr/local/epics/base/lib/linux-x86_64/libdbCore.so.3.17.0 (0x00007f36a3444000)
        libca.so.4.13.5 => /usr/local/epics/base/lib/linux-x86_64/libca.so.4.13.5 (0x00007f36a31da000)
        libCom.so.3.17.6 => /usr/local/epics/base/lib/linux-x86_64/libCom.so.3.17.6 (0x00007f36a2f67000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f36a2c60000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f36a295e000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f36a2748000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f36a237b000)
        libasyn.so => /home/epics/devel/asyn-4-41/lib/linux-x86_64/libasyn.so (0x00007f36a20d5000)
        libdbRecStd.so.3.18.1 => /usr/local/epics-devel/base-7.0.4/lib/linux-x86_64/libdbRecStd.so.3.18.1 (0x00007f36a1e81000)
        libdbCore.so.3.18.1 => /usr/local/epics-devel/base-7.0.4/lib/linux-x86_64/libdbCore.so.3.18.1 (0x00007f36a1bef000)
        libca.so.4.13.7 => /usr/local/epics-devel/base-7.0.4/lib/linux-x86_64/libca.so.4.13.7 (0x00007f36a1985000)
        libCom.so.3.18.1 => /usr/local/epics-devel/base-7.0.4/lib/linux-x86_64/libCom.so.3.18.1 (0x00007f36a1712000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f36a14f6000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f36a12b0000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f36a10a8000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f36a0ea4000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f36a416c000)
        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f36a0c7a000)
```
Note that there 2 lines for libasyn.so.  The first is "no found", which the second, further down in the output, has the correct definition.

modules/RELEASE.linux-x86_64.local contains this, which is correct:
```
corvette:~/devel/motor/modules>more RELEASE.linux-x86_64.local
MOTOR = /home/epics/devel/motor-7-0
ASYN = /corvette/home/epics/devel/asyn-4-41
SNCSEQ = /corvette/home/epics/devel/seq-2-2-5
BUSY = /corvette/home/epics/devel/busy-1-7-2
IPAC = /corvette/home/epics/devel/ipac-2-15
EPICS_BASE = /corvette/usr/local/epics-devel/base-7.0.4
SUPPORT = /corvette/home/epics/devel
```

What can be causing this problem.  It makes it so I cannot run any of the example applications.

**Comment by anjohnson** [comment]
Hi Mark, please try moving the ASYN definition below BUSY; if that doesn't help, check the order in which the asyn and busy libraries are linked. The order in which RELEASE file entries are first seen controls the order of the modules get searched when linking and the fact that you have ASYN up at the top might be the problem. I would expect to see it above EPICS_BASE but below any other module that uses it.

**Comment by MarkRivers** [comment]
I found the problem.  I had not defined BUILD_IOCS=YES in the motor/configure/RELEASE file.  I did define it in some of the submodule configure/RELEASE files.  In some cases I did not define it, but I just went to the iocs directory and typed make.  That does not seem to work.  But defining it at the top-level fixed the problem.  I don't understand this.

**Comment by anjohnson** [comment]
Hopefully you meant inside configure/CONFIG_SITE, not configure/RELEASE – the latter should really only contain paths.

**Comment by MarkRivers** [comment]
Yes, I meant CONFIG_SITE, not RELEASE.

**Comment by MarkRivers** [comment]
> Hi Mark, please try moving the ASYN definition below BUSY; if that doesn't help, check the order in which the asyn and busy libraries are linked.

That RELEASE.linux-x86_64.local is not a file that I created or edited, it is autogenerated.  The top-level motor/configure/RELEASE appears to be the wrong order.

But now I cannot reproduce the problem. I have reverted the CONFIG_SITE, done make clean and now ldd does not show the missing libasyn.so.
