### ISSUE TITLE
Missing iocsh file

### ISSUE THREAD

**Issue by djvine** [epics-motor/motorMotorSim#6]
In the xxx module, the file (xxx/iocBoot/iocxxx/examples/motors.iocsh) references that this module should have an iocsh directory:
#iocshLoad("$(MOTOR)/modules/motorMotorSim/iocsh/motorSim.iocsh", "INSTANCE=motorSim, HOME_POS=0, NUM_AXES=16, LOW_LIM=-32000, SUB=substitutions/motorSim.substitutions")

Does that file exist somewhere? I couldn't find it.

**Comment by anjohnson** [comment]
Have you actually compiled this module yet? I believe many synApps modules are now installing startup script fragments into an `$(INSTALL_LOCATION)/iocsh` directory at build time. The `motorSim.iocsh` source file can be found in the `motorSimApp/iocsh` directory of this repo, but after building, depending on where this repo was checked out, it may be found in an `iocsh` directory of the motor app itself. The path quoted in the xxx module example should probably be just `$(MOTOR)/iocsh/motorSim.iocsh` in that case.

**Comment by djvine** [comment]
Yes, compiled no errors:

make -C ./configure install 
make[1]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/configure'
make -C O.linux-x86_64 -f ../Makefile TOP=../.. \
    T_A=linux-x86_64 install
make[2]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/configure/O.linux-x86_64'
perl -CSD /opt/epics/base/bin/linux-x86_64/convertRelease.pl checkRelease
make[2]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/configure/O.linux-x86_64'
make[1]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/configure'
make -C ./motorSimApp install 
make[1]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp'
make -C ./src install 
make[2]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/src'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[3]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/src/O.linux-x86_64'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/src/O.linux-x86_64'
make[2]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/src'
make -C ./Db install 
make[2]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/Db'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[3]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/Db/O.linux-x86_64'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/Db/O.linux-x86_64'
make[2]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/Db'
make -C ./iocsh install 
make[2]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/iocsh'
make -C O.linux-x86_64 -f ../Makefile TOP=../../.. \
    T_A=linux-x86_64 install
make[3]: Entering directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/iocsh/O.linux-x86_64'
make[3]: Nothing to be done for 'install'.
make[3]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/iocsh/O.linux-x86_64'
make[2]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp/iocsh'
make[1]: Leaving directory '/opt/epics/synApps/support/motor-R7-2-1/modules/motorMotorSim/motorSimApp'


[david@dawn motorMotorSim]$ ls
configure  docs  iocs  Makefile  motorSimApp  README.md

**Comment by djvine** [comment]
Should I make a pull request updating xxx to the correct path?

motorMotorSim/motorSimApp/iocsh/motorSim.iocsh

**Comment by keenanlang** [comment]
The iocsh file for motorSim should get installed to the top-level Motor directory based off a CFG rule in the top-level synApps configure. The xxx file does need to be updated, though (as do many of the modules as a few still don't install their iocsh files).

**Comment by djvine** [comment]
@keenanlang it sounds from your description that xxx does need to be updated to find the iocsh in the top level of the Motor directory, and not the top level of the motorMotorSim directory.

Current xxx path:
#iocshLoad("$(MOTOR)/modules/motorMotorSim/iocsh/motorSim.iocsh", "INSTANCE=motorSim, HOME_POS=0, NUM_AXES=16, LOW_LIM=-32000, SUB=substitutions/motorSim.substitutions")

Correct xxx path:
#iocshLoad("$(MOTOR)/iocsh/motorSim.iocsh", "INSTANCE=motorSim, HOME_POS=0, NUM_AXES=16, LOW_LIM=-32000, SUB=substitutions/motorSim.substitutions")

Edit: Sorry - i misread your reply. I thought you said xxx did not need to be updated. You're saying that it does and I agree.
